dist: trusty
sudo: required

cache:
  directories:
  - "$HOME/google-cloud-sdk/"

git:
  depth: 10000

env:
  global:
  - PROJECT_NAME=nav-datalab
  - IMAGE_NAME=gcloud-test
  - INSTANCE_NAME=ai-lab-nace-poc
  - RELEASE_VERSION=$(git rev-list --count master)
  - SERVICE_ACCOUNT=travis-continuous-integration@${PROJECT_NAME}.iam.gserviceaccount.com
  - ZONE_TAG=us-east1-b

before_install:
  # Download and unpack gcloud SDK if not already cached
  - if [ ! -d ${HOME}/google-cloud-sdk ]; then curl https://sdk.cloud.google.com | bash; fi
  # Decrypt gcloud service account key
  - openssl aes-256-cbc -K $encrypted_23b53ae62afc_key -iv $encrypted_23b53ae62afc_iv -in client_secret.json.enc -out client_secret.json -d 
  # Autohorize access to gcloud platform using service account key
  - gcloud auth activate-service-account ${SERVICE_ACCOUNT} --key-file client-secret.json --project=${PROJECT_NAME}

jobs:
  include:
  - stage: build and push docker image to gcloud
    script:
    # Build and tag docker image
    - docker build -t ${IMAGE_NAME} .
    - docker images
    - docker tag ${IMAGE_NAME} gcr.io/${PROJECT_NAME}/${IMAGE_NAME}:${RELEASE_VERSION}
    # Push docker image to gcloud storage
    - gcloud docker -- push gcr.io/${PROJECT_NAME}/${IMAGE_NAME}:${RELEASE_VERSION}
    # Remove older docker images to conserve VM instance memory
    - gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE_TAG} --command "docker rmi
      \$(docker images | grep 'gcr.io/${PROJECT_NAME}/${IMAGE_NAME}' | awk '{print
      \$3}') | true"
  - stage: deploy docker image to gcloud VM instance
    script:
    # Update container image and restart VM instance
    - gcloud compute instances stop ${INSTANCE_NAME} --zone ${ZONE_TAG}
    - gcloud beta compute instances update-container ${INSTANCE_NAME} --container-image
      gcr.io/${PROJECT_NAME}/${IMAGE_NAME}:${RELEASE_VERSION} --zone ${ZONE_TAG}
    - gcloud compute instances start ${INSTANCE_NAME} --zone ${ZONE_TAG}
